New docs page
amarantha-k/xrpl-org-dev-portal pull request #23
Opened 2022-08-30 21:03 UTC by jonathanlei

implement new docs page design according to https://www.figma.com/file/gxbKHEJUhGPZF2gWL8Y1Zh/Docs-and-Dev-Tools-2022?node-id=1370%3A74540

2022-08-31 00:29 UTC, mDuo13 requested changes
It mostly looks good, but there are a couple places where the amount of an object that is actually a clickable link seems smaller than it should be. I like to be generous with the amount of area that is actually clickable, so users don't need to have precise dexterity to click what they wanted.

2022-08-31 00:29 UTC, mDuo13 commented on _components/pages/Docs.tsx
> +              </div>
I think the whole block—especially the icon—should be clickable, not just the text. Here's one way you could do that (I think it'll need CSS fixes to make the hover color look right for the text though):

```suggestion
              <a className="col langs" target="_blank"
                    href="https://github.com/XRPLF/xrpl.js">
                <img
                  src={prefix + "/img/docs/javascript.svg"}
                  className="circled-logo"
                ></img>
                <h5 className="btn-arrow-purple">
                    Javascript
                </h5>
              </a>
```

2022-08-31 00:29 UTC, mDuo13 commented on _components/pages/Docs.tsx
> +}
Right now, only the little tiny arrow after the text is a hyperlink. That seems wrong. I think the whole card should be a link. For example:

```suggestion
function DevToolsCard({ props }) {
  return (
    <a className="col" target="_blank" href={props.link}>
      <h6 className="btn-arrow-purple">
        {props.title}
      </h6>
      <p>{props.description}</p>
    </a>
  );
}
```

2022-09-01 00:53 UTC, mDuo13 approved these changes
Looks good to me now

2022-09-01 18:28 UTC, amarantha-k approved these changes
Looks great! Thanks @jonathanlei!

2022-09-01 18:32 UTC, merged